services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-mysql-docker:
    image: springboot-mysql-docker:latest
    container_name: springboot-mysql-docker
    depends_on:
      - mysqldb
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
